### ISSUE TITLE
Add en_DE

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/Holidays#3]
English / German is a thing, it seems. Can we use a symlink for that? As far as I know GitHub supports those.

**Comment by viktorasl** [comment]
When fixing https://github.com/GitHawkApp/GitHawk/issues/2560 I've read localization docs so the thing is that `Locale.current.identifier` will be one of `Locale.availableLocaleIdentifiers` and it will consist of: language code, often includes a region code, and occasionally a script designator.
Which means that if I have set a Portuguese language as a primary on my device and set Lithuania as my region `Locale.current.identifier` will be equal to `en_LT`.
Currently in GitHawk app case all identifiers will start w/ `en_`
Having that in mind there will be lots and lots of jsons which will be the same.

To come up w/ much more simple solution we should decide which is more important: language or region for inbox zero message:
* if language (i.e we'd like to greet people the language they prefer): I suggest taking first value from `Locale.preferredLanguages` which is a list of device languages;
* if region (we'd like to greet people with holiday in region where they live/work): I suggest  taking into account `Locale.current.regionCode` which is one of `Locale.isoRegionCodes` (255 values at the moment).

To sumarize `Locale.current.identifier` does not give enough context if app language is not important.

I personally have my language set to `English` & region to `Lithuania`.

**Comment by j-f1** [comment]
Seems like it would be best to have holidays by region rather than language.
